### ISSUE TITLE
Can't integrate with grub

### ISSUE THREAD

**Issue by arteze** [jtsiomb/pcboot#4]
I am trying to start the img with grub, in my case I am using grub 1, but it doesn't work.

Command Qemu:
```sh
qemu-system-x86_64 -boot c -m 512 -smp 2 -drive cache=none,format=raw,file=/dev/sda
```

Grub 1:
```sh
title PCBoot
	insmod fat
	insmod chain
	chainloader /floppy.img
```

Error (with strange characters):

```
...strangechars... Should not run from BOOT.INI ...strangechars...
Drv: 128 1023/255/2 Load 3072 ...strangechars...
```

This happens in qemu and also when booting from the computer.

Versions:
 - QEMU emulator version 5.2.0

**Comment by jtsiomb** [comment]
I have never tried loading it from grub, and there would be little sense in doing that, since pcboot is essentally a boot loader. If you want to use grub, you can have it just load your ELF files, you don't need pcboot for that.

**Comment by arteze** [comment]
Ahh, I didn't know it was a bootloader, so there is another problem, when I press F1 a lot of animated random colors appear, everywhere, but the system loader does not appear.

**Comment by jtsiomb** [comment]
F1 is supposed to show an animated effect in lowres, and to return back to text mode by hitting esc.

All these F-key things are just tests. pcboot is just a framework to get your bare metal code up and running. Could be used as a boot loader for an operating system, could be used as a unikernel to write bare metal bootable programs, but in either case the F-key tests, are completely unimportant.
